apiRules:
- include:
    # Including the OmiyaGames.GameFeel namespace
    uidRegex: ^OmiyaGames\.GameFeel$
    type: Namespace
- include:
    # Including the OmiyaGames.GameFeel.Editor namespace
    uidRegex: ^OmiyaGames\.GameFeel\.Editor$
    type: Namespace
- include:
    uidRegex: ^Global
    type: Namespace
- exclude:
    # Taro Omiya: note that I'm ignoring namespaces containing unit tests on purpooses
    uidRegex: .*
    type: Namespace
