apiRules:
- include:
    # Including the OmiyaGames.TimeSettings namespace
    uidRegex: ^OmiyaGames\.TimeSettings$
    type: Namespace
- include:
    # Including the OmiyaGames.TimeSettings.Editor namespace
    uidRegex: ^OmiyaGames\.TimeSettings$
    type: Namespace
- include:
    uidRegex: ^Global
    type: Namespace
- exclude:
    # Taro Omiya: note that I'm ignoring namespaces containing unit tests on purpooses
    uidRegex: .*
    type: Namespace
